# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payment_pb2 as payment__pb2


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePaymentLink = channel.unary_unary(
                '/PaymentService/GeneratePaymentLink',
                request_serializer=payment__pb2.GeneratePaymentLinkRequest.SerializeToString,
                response_deserializer=payment__pb2.GeneratePaymentLinkResponse.FromString,
                )


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePaymentLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePaymentLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePaymentLink,
                    request_deserializer=payment__pb2.GeneratePaymentLinkRequest.FromString,
                    response_serializer=payment__pb2.GeneratePaymentLinkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePaymentLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PaymentService/GeneratePaymentLink',
            payment__pb2.GeneratePaymentLinkRequest.SerializeToString,
            payment__pb2.GeneratePaymentLinkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
